---

- hosts: all
  become: true
  tasks:

  - name: install apache2 package && php packages for ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "ubuntu"

  - name: install https-centos package && php packages
    dnf:
      name:
       - httpd
       - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Centos"
