---
- name: Install nginx
  hosts: centos
  become: true

  tasks:
  - name: Add epel-release repo
    yum:
      name: epel-release
      state: present

  - name: Install nginx
    yum:
      name: nginx
      state: present
      enabled: yes

#  - name: Insert Index Page
#    template:
#      src: index.html
#      dest: /usr/share/nginx/html/index.html

  - name: Start NGiNX
    service:
      name: nginx
      state: started
#      enabled: yes
